### ISSUE TITLE
Error in opening schematic files

### ISSUE THREAD

**Issue by tightmopedman9** [14Point7/SLC-Free#1]
When trying to open the schematic/board files in Eagle (6.1 & 6.5) the following error is presented:
Error:

line 7, column 18: This is not an EAGLE file.

There appears to be no error in line 7 of the Eagle files as compared to working files.

**Comment by toalan** [comment]
Hi,

I just tried to open the schematic with the latest 6.5 version of eagle 
and it works, I have attached a zip of the eagle files.
